version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8088:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web1
      - web2
    networks:
      - backend

  web1:
    image: web1_image
    container_name: web1  # Asigna un nombre personalizado al contenedor
    ports:
      - "8001:80"
    networks:
      - backend

  web2:
    image: web2_image
    container_name: web2  # Asigna un nombre personalizado al contenedor
    ports:
      - "8002:80"
    networks:
      - backend

networks:
  backend:
